apiVersion: apps/v1
kind: Deployment
metadata:
  name: hike-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hike-app
  template:
    metadata:
      labels:
        app: hike-app
    spec:
      containers:
        - image: hike_service
          name: hike-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: hike
spec:
  type: LoadBalancer
  ports:
    - port: 8087
  selector:
    app: hike-app